### ISSUE TITLE
java.util.InputMismatchException 

### ISSUE THREAD

**Issue by luca-zamboni** [luborliu/TraClusAlgorithm#2]
Had this problem
Exception in thread "main" java.util.InputMismatchException
    at java.util.Scanner.throwFor(Scanner.java:864)
    at java.util.Scanner.next(Scanner.java:1485)
    at java.util.Scanner.nextDouble(Scanner.java:2413)
    at boliu.TraClusterDoc.onOpenDocument(TraClusterDoc.java:92)
    at boliu.Main.main(Main.java:20)

To solve this Exception add after line 75 in file TraClusterDoc the following line of code:
sc.useLocale(Locale.US);

**Comment by luborliu** [comment]
Thank you for reporting the issue and the suggestion of fix. I have updated the code. The issue will be closed.
